apiVersion: v1
kind: Service
metadata:
  name: secret-fixed-service
spec:
  type: NodePort
  selector:
    app: secret
  ports:
    - protocol: TCP
      port: 7143
      targetPort: 7143
      nodePort: 30143  # Fixed NodePort

