apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    app: secret
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secret
        octopusexport: OctopusExport
    spec:
      containers:
        - name: secret-app
          image: 'dismantl/onetimesecret'
          ports:
            - containerPort: 7143
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
